version: "3"
services:
  chart:
    image: lanntxyz/chart:latest
    ports:
      - 80:8080
    networks:
      - webnet
    volumes:
      - ./:/opt/chart
    environment:
      - REDIS_HOST=redis
  redis:
     image: redis:latest
     volumes:
        - redis_data:/data

volumes:
  redis_data:

networks:
  webnet:
