version: "3"
services:
  chart:
    image: lanntxyz/chart-server-docker:latest
    ports:
      - 80:8080
    networks:
      - webnet
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - app_data:/app
    environment:
      - REDIS_HOST=redis
    command: script/start.sh
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  app_data:
  redis_data:
networks:
  webnet:
