version: "3"
services:
  chart:
    image: lanntxyz/chart-server-docker:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: script/start.sh
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
