# SERVER
server:
  port: 8080
# DB
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useSSL=false
    username: root
    password: Abc12345
  thymeleaf:
    cache: false

# DOMA
doma:
  dialect: MYSQL
  naming: SNAKE_LOWER_CASE

# MARKET
bittrex:
  baseUrl: https://bittrex.com/api/v1.1/
  apiKey: api_key
  secret: secret_key
  devMode: false
