spring:
  application:
    name: chart
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useSSL=false
    username: root
    password: Abc12345
  redis:
    host: redis
  thymeleaf:
    cache: false

# SERVER
server:
  port: 9090

# DOMA
doma:
  dialect: MYSQL
  naming: SNAKE_LOWER_CASE

# MARKET
bittrex:
  baseUrl: https://bittrex.com/api/v1.1/
  apiKey: 16dd768cc7584c73b0e54c4c7b7eca94
  secret: f4a4b8c6498240ba8966cb11e7dab9c8
  devMode: false
