version: "3"
services:
  chart:
    image: lanntxyz/chart:latest
    ports:
      - 80:8081
    environment:
      - REDIS_HOST=redis
    volumes:
      - ../build/libs:/opt/chart
    entrypoint: exec java -jar /opt/chart/chart-0.0.1-SNAPSHOT.jar
  #redis:
  #   image: redis:latest
  #   volumes:
  #      - redis_data:/data

volumes:
  redis_data:
