version: "3"
services:
  chart:
    image: lanntxyz/chart:latest
    ports:
      - 80:8080
    environment:
      - REDIS_HOST=redis
    volumes:
      - ../build/libs:/opt/chart
      - ../../config:/opt/config
    #command: cp /opt/config/application.yml /opt/chart/application.yml
    entrypoint: java -jar /opt/chart/chart-0.0.1-SNAPSHOT.jar --spring.config.name=/opt/config/application.yml
  redis:
     image: redis:latest
     volumes:
        - redis_data:/data

volumes:
  redis_data:
